services:
  build:
    image: node:11.1.0-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && ./node_modules/webpack/bin/webpack.js"

  web:
    build:
      context: .
      dockerfile: ./build/web.Dockerfile
    ports:
      - "8082:80"